### ISSUE TITLE
Move shorthand phrases to WebIDL

### ISSUE THREAD

**Issue by domenic** [w3ctag/promises-guide#27]
(Spinning this off from #10.)

WebIDL is generally where this kind of normative spec-writing tool belongs. They'd need to get a bit more formal. We'd keep informative summaries here, probably after moving them to the WebIDL section.

**Comment by TimothyGu** [comment]
Is this still the plan?

**Comment by annevk** [comment]
Yes.

**Comment by domenic** [comment]
I think most work and discussion on this will happen over in https://github.com/heycam/webidl/issues/490. I've just left a big comment summarizing the work as I see it at https://github.com/heycam/webidl/issues/490#issuecomment-455578146. Let's leave this open for tracking, but centralize discussion over there.

**Comment by annevk** [comment]
Hurray, @Ms2ger fixed this! However, now we need to decide what to do with this document as the clashes are not great and currently causing DOM PRs to fail (e.g., https://github.com/whatwg/dom/pull/763).

**Comment by Ms2ger** [comment]
I don't know how anything works. Is https://api.csswg.org/bikeshed/ not using the same database local builds do? @tabatkins?
