### ISSUE TITLE
Call out standard naming for .loaded properties

### ISSUE THREAD

**Issue by domenic** [w3ctag/promises-guide#29]
Maybe add a partial interface for it that can be mixed in to places?

**Comment by dbaron** [comment]
@domenic Any chance you have some good examples to point to for this standard pattern?  (It would be useful to have a little more detail here, I think.)

**Comment by annevk** [comment]
I think the idea was to add `loaded` getters that return a promise which is resolved in the same task the load event is dispatched. However there was never much interest to roll this out globally (or even more limited to document loading).

**Comment by domenic** [comment]
Yeah, this is probably worth closing at this point. https://www.w3.org/2001/tag/doc/promises-guide#one-time-events covers the point well enough, albeit implicitly (by using `loaded` as an example).

**Comment by atanassov** [comment]
Given there's nothing left to be done for this issue and per @domenic suggestion, closing.
