### ISSUE TITLE
Shorthand for parallel steps

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/promises-guide#35]
Lots of specs have algorithms that http://www.w3.org/2001/tag/doc/promises-guide#explicit-async-steps suggests be written as:

1. Let _p_ be a new promise.
1. Run the following steps in parallel:
   1. Resolve _p_ with the meat of the algorithm
1. Return _p_.

Some existing algorithms, like http://www.w3.org/TR/WebCryptoAPI/#SubtleCrypto-method-encrypt, use the following pattern instead:

1. Let _p_ be a new promise.
1. Return _p_ and asynchronously perform the remaining steps.
1. Resolve _p_ with the meat of the algorithm.

A few existing algorithms, like https://html.spec.whatwg.org/multipage/webappapis.html#dom-createimagebitmap, shorten this further:

1. Return a new Promise, but continue running these steps in parallel.
1. Resolve the Promise with the meat of the algorithm.

The current recommendation requires 1-2 extra bullets for every algorithm and requires that the meat of the algorithm be indented one extra level, compared to the 2 alternatives.

Would it be possible for the TAG's promises guide to endorse "continue running these steps in parallel" and the practice of leaving the Promise unnamed when there's only 1 Promise in the algorithm?

**Comment by domenic** [comment]
This was a conscious choice, in that the suggestion given actually mirrors the code structure a lot better.

Steps that run in parallel *should* be offset from the main steps of an algorithm. And there *should not* be any steps after returning, as that makes no sense in most programming languages and so is confusing to see in pseudo-code.

If individual spec authors think they can do other styles and not confuse implementers or authors, that's fine, and probably not a big deal. But when we're giving recommendations to be applied broadly, it's better to stick to something straightforward and unambiguous.

**Comment by jyasskin** [comment]
I don't think the suggestion does mirror the code structure. In a C++11 codebase, I'd write code like this as:

```c++
WebPromise<Success, Failure> theAlgorithm(inputs) {
  return NewPromiseAndContinueInParallel<Success, Failure>(
    [](PromiseResolver<Success, Failure>& resolver) {
      // Meat of the algorithm.
    });
}
```

That does have an extra indentation level, but it puts the `return` first. Javascript lets you write code the same way. It also matches the order that things actually happen, since the return will generally precede anything that runs in parallel. (I know the return actually happens after the evaluation of the function call in the above code, but the languages let us write it first, like the specification.)

I suspect I would actually find the dangling "return" confusing (if I could find any existing specs using this style), since it makes me less sure whether anything else is happening serially. Having most algorithms say "return X and do the following in parallel" would make it more clear when an algorithm is going to kick off a parallel block in the middle of its other execution.

I do see the point that in-parallel steps should be set off from the synchronous steps. Maybe the pattern should be:

1. Return a new Promise, and run the following steps in parallel.
   1. Resolve the Promise with the meat of the algorithm.

?

**Comment by marcoscaceres** [comment]
An example of an algorithm written to return promise at the end is: 
https://fetch.spec.whatwg.org/#concept-body-consume-body

I tend to agree that "Return a new Promise, and run the following steps in parallel" makes most sense when reading. I'm curious tho, how does this play with code like:

```JS
function someSpecAlgorithm(a, b){
    if(a < b){
       return Promise.reject(new TypeError()); 
    }
    if(a === b){
       return Promise.resolve(new C()); 
    }
    return new Promise(function(){
        //async steps to create a C... 
    });
}
``` 

I tend to run into the above in my own code and I'm not entirely sure what, if any, consequences might be.

**Comment by jyasskin** [comment]
Thanks @marcoscaceres. The pattern with early resolves and rejects happens a lot in https://html.spec.whatwg.org/multipage/webappapis.html#dom-createimagebitmap, which uses the "Return a new Promise, but continue running these steps in parallel." pattern. I think your algorithm would be:

1. If `a < b`, return a promise rejected with a `TypeError` exception and abort these steps.
1. If `a === b`, return a promise resolved with a new `C` and abort these steps.
1. Otherwise, return a new promise, and run the following steps in parallel:
   1. async steps to create a C...

**Comment by domenic** [comment]
I'm *definitely* against failing to name your promises. We need to stop the implicit ambient variables in specs already. So it would need to be "return a new promise _p_, and run the following steps in parallel: ... resolve _p_."

**Comment by jyasskin** [comment]
"a new promise _p_" makes me happy.

**Comment by domenic** [comment]
I still feel skeezy putting steps after the return statement, but your arguments that this actually is how you write it in JS and (potentially) in C++ 11 have likely convinced me. Give me a night to stew on it and I can probably make the change :)

**Comment by jan-ivar** [comment]
(My 2 cents) There's a sequence to things, and nothing happens after a return. return f(); first calls f() and *then* returns its result. - so I find the "return and" construct tightly coupled, confusing and inferior.

I think what @domenic already has is outstandingly readable. It does several things nicely:
1. It forks the main sequence at the right place.
2. The indentation and the continuation of the main sequence together literally illustrate that a parallel sequence starts.
3. The parallel sequence is bracketed by the creation and return of the promise made by it.
4. It is loosely coupled.

I think the last point is important, because imagine an algorithm that has other work to do before returning, or needs to start two parallel threads. I think those cases show that the "return and" pattern is a special case we can avoid.

**Comment by jyasskin** [comment]
I definitely don't think "Return and" should be the _only_ construct that the promises-guide suggests for starting promise-work in parallel. It should be a shorthand that applies when all of the subsequent steps are actually supposed to happen in parallel. Like many shorthands for special cases, this can help readability precisely by making this common case look different from cases that have other work to do before returning, or that need to start two parallel threads.

I think item (3) in particular implies a dangerous mistake: the parallel sequence's _execution_ is not bracketed by the creation and return of the promise. Instead, the parallel sequence will generally continue executing long after the return, and it's good to emphasize that to spec readers and writers.

**Comment by jan-ivar** [comment]
No need to run stuff in parallel if we're going to wait for it, so not a likely mistake I would think.

**Comment by jyasskin** [comment]
@domenic Do you need anything else from us before deciding on a change for this?

**Comment by domenic** [comment]
After re-reading everything, I think I'd rather leave this out of the guide. People can of course do it in their own specs.

**Comment by slightlyoff** [comment]
I'm pretty sure that @marcoscaceres and @jyasskin have a strong point here. It isn't clear from reading specs that delay the return that much is won by doing it.

Consider this a vote for re-opening.
