### ISSUE TITLE
Add appendix documenting legacy patterns for asynchronous operations

### ISSUE THREAD

**Issue by markandrus** [w3ctag/promises-guide#39]
In [2.1. One-and-Done Operations](//www.w3.org/2001/tag/doc/promises-guide#one-and-done), the guide reads (emphasis mine)

> Previously, web specifications used a large variety of differing patterns for asynchronous operations. __We’ve documented these in an appendix below__, so you can get an idea of what is now considered legacy. Now that we have promises as a platform primitive, such approaches are no longer necessary.

I don't believe such and appendix is included, and it would certainly be useful (e.g. analysis of benefits/tradeoffs).

**Comment by domenic** [comment]
Wow, good catch. These were moved in https://github.com/w3ctag/promises-guide/commit/8f3a099f28980e98b402577f86f7feb14bf4dc7c but then I think the Bikeshed conversion in https://github.com/w3ctag/promises-guide/commit/e3a29434fb6ec011b24e59ee52742cd03bbae068 lost them.

**Comment by markandrus** [comment]
Thanks!
