### ISSUE TITLE
Updating deploy script

### ISSUE THREAD

**Issue by domenic** [w3ctag/promises-guide#54]
I need to update the deploy script to be more secure. In order to do this, I need the ability to add a deploy key to the repository, via the repository settings. @plinss, would you be able to make me an admin for this repository, or find some time to collaborate on IRC or similar to add the deploy key yourself?

**Comment by domenic** [comment]
Ping @plinss. Deploys are now failing, so my recently-merged changes are not visible.

**Comment by plinss** [comment]
There don't appear to be any deploy keys currently configured. I made you an admin for that repo so you should be able to set one

**Comment by domenic** [comment]
Fixed by cb14d0e13e68747524a22e1a36791175d333d819. Thanks @plinss!
